services:
  - type: web
    name: autocare-backend
    runtime: docker
    rootDir: autocare-backend
    buildCommand: "./mvnw clean package -DskipTests"
    startCommand: "java -jar target/autocare-backend-0.0.1-SNAPSHOT.jar"

    envVars:
      - key: DB_URL
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: MAIL_USERNAME
        sync: false
      - key: MAIL_PASSWORD
        sync: false
      - key: JWT_SECRET
        sync: false
